# Use a base image with Python 3.8
FROM python:3.8

# Copy the Python package files
COPY . /app

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Streamlit
RUN pip install streamlit

# Define the command to run the Streamlit app
CMD ["streamlit", "run", "app.py"]

# Expose the default Streamlit port
EXPOSE 8501
