# GitHub Actions to automatically test on sample files
name: GPU Test Cupy 11.1

on:
  workflow_dispatch:

jobs:
  GPU_Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: |
        conda create --name alphastats_gpu python=3.8 -y
        conda activate alphastats_gpu
        pip install ".[stable,gui-stable]"
        pip install pymongo
        pip install dnspython
        pip install wget
        pip install cupy-cuda111s
    - name: Run CPU test script
      run: |
        conda activate alphastats_gpu
        python test_gpu_.py numba-multithread
    - name: Run GPU test script
      run: |
        conda activate alphastats_gpu
        python test_gpu_.py cuda
